export const LOGINTOGGLE = 'LOGINTOGGLE'
export const SIGNUPTOGGLE = 'SIGNUPTOGGLE'
export const BOOKNAME = 'BOOKNAME'
export const ARRAYLIST = 'ARRAYLIST'
export const ARRAYWISHLIST = 'ARRAYWISHLIST'
export const ADDQUENTITY = 'ADDQUENTITY'
export const SUBQUENTITY = 'SUBQUENTITY'
export const PLACEORDERKEY = 'PLACEORDERKEY'
export const CONTINUESKEY = 'CONTINUESKEY'


